const contenidoCarrito = document.getElementById ("contenidoCarrito")
const productos = [
    {
        id: 1,
        nombre:"Bolso artesanal Azul",
        precio: 25000,
        img:"../img/bolso-azul-2.jpeg",
        cantidad:1,
    },
    {
        id: 2,
        nombre:"Bolso artesanal Azul y plateado",
        precio: 25000,
        img:"../img/bolso-azul.jpeg",
        cantidad:1,
    },
    {
        id: 3,
        nombre:"Bolso artesanal Rojo",
        precio: 25000,
        img:"../img/bolso-rojo.jpeg",
        cantidad:1,
    },
    {
        id: 4,
        nombre:"Bolso artesanal Salmón",
        precio: 25000,
        img:"../img/bolso-salmon.jpeg",
        cantidad:1,
    },
    {
        id: 5,
        nombre:"Bolso artesanal Verde",
        precio: 25000,
        img:"../img/bolso-verde.jpeg",
        cantidad:1,
    },
    {
        id: 6,
        nombre:"Bolso artesanal Negro",
        precio: 25000,
        img:"../img/bolso-negro.jpeg",
        cantidad:1,
    },
    {
        id: 7,
        nombre:"Tolla artesanal Blanca",
        precio: 15000,
        img:"../img/taolla-blanca.jpeg",
        cantidad:1,
    },
    {
        id: 8,
        nombre:"Tolla artesanal Verde",
        precio: 15000,
        img:"../img/toalla-verde.jpeg",
        cantidad:1,
    },
    {
        id: 9,
        nombre:"Tolla artesanal Azul",
        precio: 15000,
        img:"../img/taolla-azul.jpeg",
        cantidad:1,
    },
    {
        id: 10,
        nombre:"Tolla artesanal Rosa",
        precio: 15000,
        img:"../img/toalla-rosa-fuerte.jpeg",
        cantidad:1,
    },
    {
        id: 11,
        nombre:"Tolla artesanal Rosa pastel",
        precio: 15000,
        img:"../img/toalla-rosa.jpeg",
        cantidad:1,
    },
    {
        id: 12,
        nombre:"Bandeja chica Beige con flores",
        precio: 7500,
        img:"../img/bandeja-chica1.jpeg",
        cantidad:1,
    },
    {
        id: 13,
        nombre:"Bandeja chica Gris con flores",
        precio: 7500,
        img:"../img/bandeja-chica2.jpeg",
        cantidad:1,
    },
    {
        id: 14,
        nombre:"Bandeja chica Rosa con flores",
        precio: 7500,
        img:"../img/bandeja-chica3.jpeg",
        cantidad:1,
    },
    {
        id: 15,
        nombre:"Bandeja mediana Celeste con flores",
        precio: 10000,
        img:"../img/bandeja-mediana1.jpeg",
        cantidad:1,
    },
    {
        id: 16,
        nombre:"Bandeja mediana Blanca con flores",
        precio: 10000,
        img:"../img/bandeja-mediana2.jpeg",
        cantidad:1,
    },
    {
        id: 17,
        nombre:"Bandeja grande Blanca con flores grandes",
        precio: 12500,
        img:"../img/bandeja-grande1.jpeg",
        cantidad:1,
    },
    {
        id: 18,
        nombre:"Bandeja grande Blanca con flores chicas",
        precio: 12500,
        img:"../img/bandeja-grande2.jpeg",
        cantidad:1,
    },
    {
        id: 19,
        nombre:"Bandeja grande Gris con flores",
        precio: 12500,
        img:"../img/bandeja-grande3.jpeg",
        cantidad:1,
    },
    {
        id: 20,
        nombre:"Bandeja Extra-Grande gris con flores",
        precio: 15000,
        img:"../img/bandeja-extraGrande1.jpeg",
        cantidad:1,
    },
    {
        id: 21,
        nombre:"Bandeja Extra-Grande Marrón con flores",
        precio: 15000,
        img:'../img/bandeja-extraGrande2.jpeg',
        cantidad:1,
    },
]